/**
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm.arduinoML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.drago.arduinoml.dm.arduinoML.ArduinoMLPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
