/**
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm.ui.contentassist;

import com.drago.arduinoml.dm.ui.contentassist.AbstractArduinoMLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ArduinoMLProposalProvider extends AbstractArduinoMLProposalProvider {
}
