/**
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm.validation;

import com.drago.arduinoml.dm.validation.AbstractArduinoMLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ArduinoMLValidator extends AbstractArduinoMLValidator {
}
