/**
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm;

import com.drago.arduinoml.dm.AbstractArduinoMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ArduinoMLRuntimeModule extends AbstractArduinoMLRuntimeModule {
}
