/**
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm;

import com.drago.arduinoml.dm.ArduinoMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ArduinoMLStandaloneSetup extends ArduinoMLStandaloneSetupGenerated {
  public static void doSetup() {
    new ArduinoMLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
