/*
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ArduinoMLRuntimeModule extends AbstractArduinoMLRuntimeModule {
}
