/*
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ArduinoMLStandaloneSetup extends ArduinoMLStandaloneSetupGenerated {

	def static void doSetup() {
		new ArduinoMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
