/*
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractArduinoMLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.drago.arduinoml.dm.arduinoML.ArduinoMLPackage.eINSTANCE);
		return result;
	}
}
