/*
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArduinoMLScopeProvider extends DelegatingScopeProvider {
}
