/**
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm.ide;

import com.drago.arduinoml.dm.ide.AbstractArduinoMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ArduinoMLIdeModule extends AbstractArduinoMLIdeModule {
}
