/**
 * generated by Xtext 2.16.0
 */
package com.drago.arduinoml.dm.ide;

import com.drago.arduinoml.dm.ArduinoMLRuntimeModule;
import com.drago.arduinoml.dm.ArduinoMLStandaloneSetup;
import com.drago.arduinoml.dm.ide.ArduinoMLIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ArduinoMLIdeSetup extends ArduinoMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    ArduinoMLRuntimeModule _arduinoMLRuntimeModule = new ArduinoMLRuntimeModule();
    ArduinoMLIdeModule _arduinoMLIdeModule = new ArduinoMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_arduinoMLRuntimeModule, _arduinoMLIdeModule));
  }
}
